--- #YAML:1.0
name:               Perlbal-Plugin-Addheader
version:            0.01
abstract:           Add Headers to Perlbal webserver responses
author:
    - Bruno Martins <bruno.martins@co.sapo.pt>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Perlbal:     1.72
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
